/*
    This is an example pipeline that implement full CI/CD for a simple static web site packed in a Docker image.
    The pipeline is made up of 6 main steps
    1. Git clone and setup
    2. Build and local tests
    3. Publish Docker and Helm
    4. Deploy to dev and test
    5. Deploy to staging and test
    6. Optionally deploy to production and test
 */


/*
    Create the kubernetes namespace
 */
def createNamespace (name) {
    echo "Creating namespace ${name} if needed"
    sh "kubectl create namespace ${name} --dry-run -o yaml | kubectl apply -f -"
}

/*
    Helm install Notifier application
*/
def helmDryrunNotifier (notifierReleaseName) {
    echo "Installing notifier application"

    script {
       // sh "helm repo add helm ${HELM_REPO}; helm repo update"
       sh "upgrade --dry-run --debug --install ${notifierReleaseName} --namespace=api --set image.repository='${image}' database.url='${hostname}',secret.awscred.aws_key=${env.awsKey},secret.awscred.secret_key=${env.awsSecret},secret.regcred.dockerconfigjson=${env.dockerString} --debug ./notifier/"
    }
}

/*
    Helm install notifier application
*/
def helmInstallNotifier (notifierReleaseName) {
    echo "Installing notifier application"

    script {
       // sh "helm repo add helm ${HELM_REPO}; helm repo update"
       sh "helm upgrade --install ${notifierReleaseName} --namespace=api --set image.repository='${image}' database.url='${hostname}',secret.awscred.aws_key=${env.awsKey},secret.awscred.secret_key=${env.awsSecret},secret.regcred.dockerconfigjson=${env.dockerString} --debug ./notifier/"
    }
}

node {
     def changedFiles
     def image = "achirashah/notifier:notifier"
     def notifierReleaseName = "notifier"
     def kubernetesCredentials = 'KubeCreds'

    stage('Clone repository') {
        /* Cloning the Repository to our Workspace */
        checkout scm
        sh 'git diff --name-only --diff-filter=ADMR @~..@ > output.txt'
        changedFiles = readFile 'output.txt'
        echo "Changed files - ${changedFiles}"
    }

    stage('Startup activities'){
        echo "${env.ServerUrl}"
        withKubeConfig([credentialsId: kubernetesCredentials,
                        serverUrl: "${env.ServerUrl}"
                        ]) {
          sh "kubectl cluster-info"
        }


        // Init helm client
        sh "helm init"
    }
    try {
        stage ('helm test') {
            helmDryrunNotifier (notifierReleaseName)
        }
        stage('Deploy Notifier'){
            if (changedFiles?.trim().contains("notifier")){
                echo "Deploying notifier"
                withKubeConfig([credentialsId: kubernetesCredentials,
                                 serverUrl: "${env.ServerUrl}"
                              ]) {
                       createNamespace('api')
                       helmInstallNotifier(notifierReleaseName)
                }

            }else{
                echo "Nothing to deploy in notifier"
            }
        }
        catch (Exception err){
            err_msg = "Test had Exception(${err})"
            currentBuild.result = 'FAILURE'
            error "FAILED - Stopping build for Error(${err_msg})"
        }
    }
}